### ISSUE TITLE
Fixed values in channel_setup altered by output correction

### ISSUE THREAD

**Issue by francais01** [Breina/ha-artnet-led#19]
The addition of fixed values in channel setup is great, I use it to set the mode to RGB on a light, so my `channel_setup` is: 215,r,g,b.
However, I had quadratic output correction enabled, so I was getting 181 instead of 215. It looks like the correction is applied to all channels, regardless of their type.

**Comment by Breina** [comment]
Good call!
This behaviour is controlled by a library, so currently I can't fix it directly. I'm slowly in the process of building my own client, then I'll take care of this.

**Comment by Breina** [comment]
I think it might be better to configure your 215 channel as a separate `fixed`  light entry, instead of combining it within a light with output correction. Architecturally, it would add too much complexity, in my opinion.

**Comment by mvandenabeele** [comment]
I update Home Assistant to 2023.6.2 today and this integration to 0.1.9 but I think there really is an issue with the fixed channel values. I tried removing output_correction but that didn't help. Then I tried adding output_correction again, but with linear explicitly set. I can't check but the values must be off since all dimmerpacks that need specific setup values don't work anymore.

Here's my configuration:

```
- platform: artnet_led
  host: 192.168.113.72
  max_fps: 25 # Max 40 per second
  refresh_every: 0 # Resend values if no fades are running every x seconds, 0 disables automatic refresh
  universes: # Support for multiple universes
    0: # Nr of Universe (see configuration of your Art-Net Node)
      output_correction: linear # optional: output correction for the whole universe, will be used as default if nothing is set for the channel
      devices:
        #SP4LED Module 1
        - channel: 1
          name: sp4led_1_dimmer
          type: fixed
          channel_setup:
            - 255
        - channel: 2
          name: sp4led_1_program
          type: fixed
          channel_setup:
            - 0
        - channel: 3
          name: sp4led_1_config
          type: fixed
          channel_setup:
            - 255
        - channel: 4
          name: badkamer.hoofdlamp
        - channel: 5
          name: badkamer.spots_douche
        - channel: 6
          name: badkamer.spots_lavabo
        - channel: 7
          name: tr.hoofdlamp
        #SP4LED Module 2
        - channel: 10
          name: sp4led_2_dimmer
          type: fixed
          channel_setup:
            - 255
        - channel: 11
          name: sp4led_2_program
          type: fixed
          channel_setup:
            - 0
        - channel: 12
          name: sp4led_2_config
          type: fixed
          channel_setup:
            - 255
        - channel: 13
          name: slpkmr_sam.hoofdlamp
        - channel: 14
          name: slpkmr_sam.nachtlamp
        - channel: 15
          name: slpkmr_tijl.hoofdlamp
        - channel: 16
          name: slpkmr-tijl.nachtlamp
        #SP4LED Module 3
        - channel: 30
          name: sp4led_3_dimmer
          type: fixed
          channel_setup:
            - 255
        - channel: 31
          name: sp4led_3_program
          type: fixed
          channel_setup:
            - 0
        - channel: 32
          name: sp4led_3_config
          type: fixed
          channel_setup:
            - 255
        - channel: 33
          name: slpkmr_ouders.hoofdlamp
        - channel: 34
          name: slpkmr_ouders.leeslamp_l
        - channel: 35
          name: slpkmr_ouders.leeslamp_r
        - channel: 36
          name: slpkmr_ouders.nachtlamp
        #SP4LED Module 4
        - channel: 38
          name: sp4led_4_dimmer
          type: fixed
          channel_setup:
            - 255
        - channel: 39
          name: sp4led_4_program
          type: fixed
          channel_setup:
            - 0
        - channel: 40
          name: sp4led_4_config
          type: fixed
          channel_setup:
            - 255
        - channel: 41
          name: nachthal.hoofdlamp
        - channel: 42
          name: nachthal.nachtlamp
        - channel: 43
          name: toilet_boven.hoofdlamp
        - channel: 44
          name: bureau_boven.hoofdlamp
        #SP4LED Module 5
        - channel: 46
          name: sp4led_5_dimmer
          type: fixed
          channel_setup:
            - 255
        - channel: 47
          name: sp4led_5_program
          type: fixed
          channel_setup:
            - 0
        - channel: 48
          name: sp4led_5_config
          type: fixed
          channel_setup:
            - 255
        - channel: 49
          name: hal.hoofdlamp
        - channel: 50
          name: vestiaire.hoofdlamp
        - channel: 51
          name: toilet_beneden.hoofdlamp
        - channel: 52
          name: sas.hoofdlamp
        #SP4LED Module 6
        - channel: 54
          name: sp4led_6_dimmer
          type: fixed
          channel_setup:
            - 255
        - channel: 55
          name: sp4led_6_program
          type: fixed
          channel_setup:
            - 0
        - channel: 56
          name: sp4led_6_config
          type: fixed
          channel_setup:
            - 255
        - channel: 57
          name: zitplaats.hoofdlamp
        - channel: 58
          name: zitplaats.tablet_l
        - channel: 59
          name: zitplaats.tablet_r
        - channel: 60
          name: zitplaats.hoek
        #SP4LED Module 7
        - channel: 62
          name: sp4led_7_dimmer
          type: fixed
          channel_setup:
            - 255
        - channel: 63
          name: sp4led_7_program
          type: fixed
          channel_setup:
            - 0
        - channel: 64
          name: sp4led_7_config
          type: fixed
          channel_setup:
            - 255
        - channel: 65
          name: wasplaats.hoofdlamp
        - channel: 66
          name: voorplaats.hoofdlamp_n
        - channel: 67
          name: voorplaats.bureau
        - channel: 68
          name: voorplaats.hoofdlamp_z
        #SP4LED Module 8
        - channel: 70
          name: sp4led_8_dimmer
          type: fixed
          channel_setup:
            - 255
        - channel: 71
          name: sp4led_8_program
          type: fixed
          channel_setup:
            - 0
        - channel: 72
          name: sp4led_8_config
          type: fixed
          channel_setup:
            - 255
        - channel: 73
          name: garage.hoofdlamp
        - channel: 74
          name: zolder.hoofdlamp
        - channel: 75
          name: kelder.hoofdlamp
        - channel: 76
          name: reserve_1
        #DMX Module in elektriciteitskast TR
        - channel: 80
          name: keuken.pad
        - channel: 81
          name: keuken.aanrecht
        - channel: 82
          name: keuken.tafel
        - channel: 83
          name: bureau_lr.hoofdlamp
        - channel: 84
          name: eetplaats.muur
        - channel: 86
          name: terras
        - channel: 87
          name: eetplaats.rail_3
```

I'll try setting up a dev environment to check, but I think I'll need to downgrade using my backup for the time being (Can't sleep with the lights on ;-) )
