### ISSUE TITLE
Scene transition time is ignored

### ISSUE THREAD

**Issue by m7r** [Breina/ha-artnet-led#29]
First of all thanks for this integration.

Creating scenes work like a charm and they could be switched easily with the activate buttons.
But a service call with transition will ignore the transition time
```yaml
service: scene.turn_on
data: 
  transition: 20
```

Issue arise as state transition overwrites scene transition. [I solved it for me in this way](https://github.com/m7r/ha-artnet-led/commit/f5245dd7e17a6c8682a222321b248fd0ee678a12)
