### ISSUE TITLE
Version 1.8: Green and blue channels have been swapped

### ISSUE THREAD

**Issue by m7r** [Breina/ha-artnet-led#32]
After update to 1.8 my RGB lights are incorrect. It seems green and blue channels have been swapped.
Gone back to version 1.7.

**Comment by Breina** [comment]
Given [the code](https://github.com/Breina/ha-artnet-led/compare/v0.1.7...v0.1.8), I don't feel this should be possible.

Please give me the config of this particular light, so that I may be able to reproduce this.

**Comment by m7r** [comment]
I don't know what the issue was. Made the update to 1.8 again and it is working now.
Sorry for false alarm.

For completeness this is my simple test config
```yaml
- platform: artnet_led
  node_type: artnet-direct
  host: 192.168.10.90
  max_fps: 30
  refresh_every: 4
  universes:
    0:
      send_partial_universe: True
      output_correction: linear
      devices:
        - channel: 1
          name: Spot 1
          type: rgbw
          channel_setup: dRGBW
```
