### ISSUE TITLE
Include an option to set the entity ID

### ISSUE THREAD

**Issue by PKCubed** [Breina/ha-artnet-led#75]
Is it possible to add the option to set the entity ID of a fixture in the configuration yaml file? It seems that sometimes when I change the configuration and reboot home assistant, the entity IDs will change and things get all messed up. If I could set them in the configuration file, my life would be a lot easier. Is that possible? Thanks!

**Comment by honza-kasik** [comment]
+1 on this. It could be done just like mqtt integration does it:

```yaml
mqtt:
  - light:
      name: "My favorite light"
      unique_id: "my_favorite_light_id"
      schema: json
      brightness: true
      command_topic: "home/light/1"
```

My guess is that the unique_id is created here https://github.com/Breina/ha-artnet-led/blob/main/custom_components/artnet_led/light.py#L186 . If I'm right, I can take a look at it...
