### ISSUE TITLE
Support for additional color channels like UV

### ISSUE THREAD

**Issue by roennieinator** [Breina/ha-artnet-led#82]
I have some DMX lights that have additional color channels, like amber, a separate white channel and UV.
I would like to be able to address them with Home assistant. 
Currently, I have them integrated with dRGB only. 

```
        - channel: 83
          name: "1.1"
          type: rgb
          channel_setup: 
            - d
            - R
            - G
            - B
```
